# name: main
# on:
#   push:
#     brnaches:
#       - master
#   schedule:
#     - cron: "0 0 0 0 6"
# jobs:
#   docker:
#     name: build container
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - run: docker login registry -u USER -p $TOKEN
#         env:
#           TOKEN: ${{ secrets.PAT }}
#       - run: docker build -t docker.pkg.github.com/USER/REPO/REPO:${GITHUB_SHA:0:7} -t docker.pkg.github.com/USER/REPO/REPO:latest .
#       - run: docker push docker.pkg.github.com/USER/REPO/REPO:${GITHUB_SHA:0:7} docker.pkg.github.com/USER/REPO/REPO:latest
