name: workflow
on:
  push:
    brnaches:
      - master
  schedule:
    - cron: "* * */5 * *"
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
#   docker:
#     name: build container
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - run: docker login registry -u USER -p $TOKEN
#         env:
#           TOKEN: ${{ secrets.PAT }}
#       - run: docker build -t docker.pkg.github.com/USER/TEMPLATE/TEMPLATE:${GITHUB_SHA:0:7} -t docker.pkg.github.com/USER/TEMPLATE/TEMPLATE:latest .
#       # push one at a time
#       - run: docker push docker.pkg.github.com/USER/TEMPLATE/TEMPLATE:${GITHUB_SHA:0:7}
#       - run: docker push docker.pkg.github.com/USER/TEMPLATE/TEMPLATE:latest
